### ISSUE TITLE
Gnosis chain withdrawal transaction successful. Withdrawal not appearing in receipt address on Ethereum.

### ISSUE THREAD

**Issue by lentils79** [tornadocash/tornado-nova#20]

**Comment by poma** [comment]
We can't troubleshoot it when you don't specify anything about tx. Post tx hash or something

**Comment by lentils79** [comment]
0x83a46c512535b2a6b82f3d4393cadb4de572045fdddd09c8cf39d2789b0e94bf

**Comment by lentils79** [comment]
> We can't troubleshoot it when you don't specify anything about tx. Post tx hash or something

0x83a46c512535b2a6b82f3d4393cadb4de572045fdddd09c8cf39d2789b0e94bf
