### ISSUE TITLE
Withdrawal Transaction not received

### ISSUE THREAD

**Issue by lentils79** [tornadocash/tornado-nova#21]
Gnosis chain withdrawal transaction successful. Withdrawal not appearing in receipt address on Ethereum.

txn 0x83a46c512535b2a6b82f3d4393cadb4de572045fdddd09c8cf39d2789b0e94bf

**Comment by poma** [comment]
Fixed. The problem was in xDai bridge worker that is supposed to execute mainnet transaction after the message is bridged. All such stuck transactions should be executed now.
