### ISSUE TITLE
Shielded balance never appeared

### ISSUE THREAD

**Issue by lentils79** [tornadocash/tornado-nova#33]
L1 tx is ok
Bridge tx is ok
L2 tx is ok, because it deposited the funds into Tornado pool.

Shielded balance never appeared after funding account. When logging in using private key, it says 'account not created'. When logging in via metamask, shielded amount never appears.

Is there a way this can be resolved, or are funds lost?

**Comment by officialsupport-ui** [comment]
Kindly get in touch to get this issue resolved
